### ISSUE TITLE
Limiting block placement by permission groups

### ISSUE THREAD

**Issue by Silthus** [Silthus/sLimits#1]
**Is your feature request related to a problem? Please describe.**
There was a [Limits Plugin](https://www.spigotmc.org/resources/limits.29791/) that could limit the amount of blocks placed based on permission groups and some other integrations. However it does not work since Minecraft 1.12.

**Describe the solution you'd like**
The plugin should limit the amount of blocks of a certain type a player can place based on his permission group.

- [x] Limit the amount of a block type the player can place
- [x] When a block of a certain type is placed, it is added the the players limit. 
- [x] When a previously placed limited block is destroyed it is subtracted from the players limit.
- [x] If the player is unable to place the block it should not be added to their limits.
- [x] Store the placed blocks and count to flat files.
- [x] `/limits` command to see what the limits are.

/cc @Trevor1097

**Comment by Silthus** [comment]
Here is a draft for the main config. Note that the sub section `limits` can also be devided into separate configs inside a sub folder. Each config representing a different set of limits.

If using this decentralized configuration, the unique name (path + filename) will be the id and can be omitted inside the config.

`config.yaml`
```yaml
storage: flat
limits:
  - !block-placement
# the id defines the permission, if the permission scope is set.
# permission: slimits.limit.bedrock
    id: bedrock
# whitelist mode only allows placing the defined blocks with the defined limit
# blacklist would allow placing all blocks and only limit the defined ones
    mode: whitelist
# different scopes could be added over time to scope the limit to certain events
# e.g.: worldguard, 
    scopes:
      - !scope:permission
         enabled: true
    blocks:
        bedrock: 5
        dirt: 10
```
