### ISSUE TITLE
Scoping of limits to plugins, worlds, etc.

### ISSUE THREAD

**Issue by Silthus** [Silthus/sLimits#7]
**Is your feature request related to a problem? Please describe.**
Currently there is no way of limiting a limit to only apply in a certain scope, e.g. the Nether, a WorldGuard region, a SkyBlock island, etc.

**Describe the solution you'd like**
It should be possible to configure limit scopes for each limit that limits the limit to only apply in a certain scope. The default permission would also be a scope.

Here is a draft how a limit config could look like:

```yaml
# this is the new scope config
scopes:
    # change the default permission to a custom one
    # replaces the top level 'permission: my-permision' config node
    # this means the player needs the my-custom-permission node for this config to be applied
  - type: 'default:permission'
    with:
      permission: my-custom-permission
    # by default this scope applies this limit to all worlds
    # you can override the worlds parameter to limit it to certain worlds
  - type: 'default:worlds'
    with:
      worlds:
        - world_nether
    # you can also disable scopes
    # disabling the exclude-op scope means that this limit
    # will apply to all player regardless if the have the exclude permission or not
  - type: 'default:exclude-permission'
    enabled: false
    with:
      permission: 'slimits.admin.exclude'
    # An example for a custom scope that only applies the limit if the player is inside the worldguard region
  - type: 'worldguard:region'
    with:
      regions:
        - spawn
blocks:
  BEDROCK: 5
  DIRT: 2
  STONE: 500
```

**Additional context**
Not sure yet how the different limit modes (ADD, SUBTRACT, ABSOLUTE) would play with this.
